/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.Date;

import javax.swing.*;

import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author Deepak
 */
public class index extends javax.swing.JFrame  implements ActionListener{
	private JPopupMenu popupMenu;
	private JTextField subject;
	private JMenuItem View;
	private JMenuItem delete;
	private javax.swing.JCheckBox attachment1;
	private javax.swing.JButton backup;
	private org.jdesktop.swingx.JXDatePicker date;
	private javax.swing.JLabel date1;
	private javax.swing.JComboBox drive;
	private org.jdesktop.swingx.JXDatePicker fdate;
	private javax.swing.JTextField from;
	private javax.swing.JLabel from1;
	private javax.swing.JLabel from2;
	private javax.swing.JLabel from3;
	private javax.swing.JLabel from4;
	private javax.swing.JLabel from5;
	private javax.swing.JLabel from7;
	private javax.swing.JButton jButton3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JProgressBar jProgressBar1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField mailid;
	private javax.swing.JTable mails;
	private javax.swing.JPasswordField password;
	private javax.swing.JPanel search;
	private javax.swing.JLabel subject2;
	private javax.swing.JLabel subject3;
	private org.jdesktop.swingx.JXDatePicker tdate;
	private javax.swing.JTextField to;
	private javax.swing.JLabel to1;

	// End of variables declaration
	/**
	 * Creates new form index
	 */
	public index() {
		initComponents();
		File[] drives = File.listRoots();
		if (drives != null && drives.length > 0) {
			for (File aDrive : drives) {

				drive.addItem(aDrive);
			}
		}
	}
	 

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		search = new javax.swing.JPanel();
		date1 = new javax.swing.JLabel();
		from1 = new javax.swing.JLabel();
		to1 = new javax.swing.JLabel();
		subject2 = new javax.swing.JLabel();
		subject3 = new javax.swing.JLabel();
		attachment1 = new javax.swing.JCheckBox();
		jButton3 = new javax.swing.JButton();
		to = new javax.swing.JTextField();
		from = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		mails = new javax.swing.JTable();
		date = new org.jdesktop.swingx.JXDatePicker();
		subject = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		from2 = new javax.swing.JLabel();
		mailid = new javax.swing.JTextField();
		from3 = new javax.swing.JLabel();
		password = new javax.swing.JPasswordField();
		from4 = new javax.swing.JLabel();
		from5 = new javax.swing.JLabel();
		backup = new javax.swing.JButton();
		drive = new javax.swing.JComboBox();
		from7 = new javax.swing.JLabel();
		fdate = new org.jdesktop.swingx.JXDatePicker();
		tdate = new org.jdesktop.swingx.JXDatePicker();
		jProgressBar1 = new javax.swing.JProgressBar();

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		search.setBackground(new java.awt.Color(255, 255, 255));

		date1.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		date1.setText("Date");

		from1.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		from1.setText("From");

		to1.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		to1.setText("To");

		subject2.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		subject2.setText("Subject");

		subject3.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		subject3.setText("Has attachment");

		attachment1.setBackground(new java.awt.Color(255, 255, 255));
		attachment1.setForeground(new java.awt.Color(102, 255, 255));

		jButton3.setBackground(new java.awt.Color(255, 0, 0));
		jButton3.setFont(new java.awt.Font("Traditional Arabic", 3, 14)); // NOI18N
		jButton3.setForeground(new java.awt.Color(255, 255, 255));
		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
		jButton3.setText("search");
		jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jButton3MouseEntered(evt);
			}
		});
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton3ActionPerformed(evt);
				} catch (ClassNotFoundException | SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		mails.setFont(new java.awt.Font("Traditional Arabic", 2, 12)); // NOI18N
		mails.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { }, new String[] { "From", "Subject","Has attachment" }));
		mails.setRowSelectionAllowed(true);
		
		mails.setToolTipText("right click for menu");
		popupMenu = new JPopupMenu();
		View = new JMenuItem("View");
		delete = new JMenuItem("Delete");
		popupMenu.add(View);
		popupMenu.add(delete);
		mails.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
					Point point = evt.getPoint();
					int currentRow = mails.rowAtPoint(point);
					 ListSelectionModel model = mails.getSelectionModel();
						model.setSelectionInterval( currentRow, currentRow );
			}
		});
		mails.setComponentPopupMenu(popupMenu);
		 View.addActionListener(this);
		 delete.addActionListener(this);
		
		jScrollPane1.setViewportView(mails);

		javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
		search.setLayout(searchLayout);
		searchLayout.setHorizontalGroup(
				searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(searchLayout
						.createSequentialGroup().addGroup(searchLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										searchLayout.createSequentialGroup().addGap(10, 10, 10).addGroup(searchLayout
												.createParallelGroup(
														javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(searchLayout.createSequentialGroup().addGroup(searchLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(searchLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(date1,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 34,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(from1))
														.addComponent(to1, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(subject2))
														.addGap(105, 105, 105)
														.addGroup(searchLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jButton3)
																.addGroup(searchLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(date,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(from,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				212, Short.MAX_VALUE)
																		.addComponent(to).addComponent(subject,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				212, Short.MAX_VALUE))))
												.addGroup(searchLayout.createSequentialGroup().addComponent(subject3)
														.addGap(96, 96, 96).addComponent(attachment1))))
								.addGroup(searchLayout.createSequentialGroup().addContainerGap().addComponent(
										jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(0, 33, Short.MAX_VALUE)));
		searchLayout.setVerticalGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(searchLayout.createSequentialGroup().addGap(10, 10, 10)
						.addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(date1).addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(11, 11, 11)
						.addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(from1).addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(6, 6, 6)
						.addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(searchLayout.createSequentialGroup().addGap(2, 2, 2).addComponent(to1))
								.addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(14, 14, 14)
						.addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(subject2).addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(11, 11, 11)
						.addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(subject3).addComponent(attachment1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Search", search);

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		from2.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		from2.setText("Mail id");

		from3.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		from3.setText("Password");

		password.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passwordActionPerformed(evt);
			}
		});

		from4.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		from4.setText("From");

		from5.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		from5.setText("Till");

		backup.setBackground(new java.awt.Color(255, 0, 0));
		backup.setFont(new java.awt.Font("Traditional Arabic", 3, 14)); // NOI18N
		backup.setForeground(new java.awt.Color(255, 255, 255));
		backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-add.png"))); // NOI18N
		backup.setText("Backup");
		backup.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					backupActionPerformed(evt);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		drive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "choose drive" }));
		drive.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				driveActionPerformed(evt);
			}
		});

		from7.setFont(new java.awt.Font("Vani", 1, 12)); // NOI18N
		from7.setText("Chooe directory");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout
										.createSequentialGroup().addComponent(backup).addGap(141, 141, 141))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel4Layout.createSequentialGroup()
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(from7, javax.swing.GroupLayout.PREFERRED_SIZE,
																108, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(from3).addComponent(from2)
														.addComponent(from4, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(from5, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(password).addComponent(mailid)
														.addComponent(drive, 0, 186, Short.MAX_VALUE)
														.addComponent(fdate, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(tdate, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(76, 76, 76)))));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(mailid, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(from2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(from3))
						.addGap(8, 8, 8)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(from4).addComponent(fdate, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(from5).addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(drive, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(from7, javax.swing.GroupLayout.Alignment.TRAILING))
						.addGap(31, 31, 31).addComponent(backup).addGap(20, 20, 20)));

		jProgressBar1.setMinimum(50);
		jProgressBar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
			public void propertyChange(java.beans.PropertyChangeEvent evt) {
				jProgressBar1PropertyChange(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(24, 24, 24)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 556,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(555, 555, 555)))));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(23, 23, 23)
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(170, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Backup", jPanel2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jTabbedPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0,
								0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jTabbedPane1).addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void backupActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException {
		String mail = mailid.getText();
		Date fd = fdate.getDate();
		Date td = tdate.getDate();
		boolean testMailId;
		Pattern patternMail;
		Matcher matcherMail;
		final String MAIL_PATTERN = "^[_A-Za-z0-9\\+]+(\\.[_A-Za-z0-9-]+)*@"
				+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
		patternMail = Pattern.compile(MAIL_PATTERN);
		matcherMail = patternMail.matcher(mail);
		testMailId = matcherMail.matches();
		if (testMailId) {
			if (fd.before(td)) {
				String host = "pop.gmail.com";
				String port = "995";
				String userName = mailid.getText();
				String passwrd = password.getText();
				String selDrive = drive.getSelectedItem().toString();
				/*
				 * Date startDate = new
				 * SimpleDateFormat("yyyy-MM-dd").parse("2014-06-30"); Date
				 * endDate = new
				 * SimpleDateFormat("yyyy-MM-dd").parse("2017-06-01");
				 */
				String saveDirectory = "D:\\Backup";
				EmailReader receiver = new EmailReader();
				receiver.setSaveDirectory(saveDirectory);
				EmailReader email = new EmailReader();
				try {
					email.downloadEmailAttachments(host, port, userName, passwrd, selDrive, fd, td);
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			} else {
				JOptionPane.showMessageDialog(null, "start date greater than till date");
			}
		} else {
			JOptionPane.showMessageDialog(null, "Enter a vaild mailId");
		}
	}

	private void passwordActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jProgressBar1PropertyChange(java.beans.PropertyChangeEvent evt) {

	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {

		System.out.println("Action occured::" + evt.getActionCommand());
		ArrayList<File> files = new ArrayList<>();
		Set<File> hs = EmailReader.listf("D:/MailBackup", files,mails);
	}

	private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void driveActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		final index i = new index();

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				i.setVisible(true);
				i.setResizable(false);
			}
		});
	}
	/****************Action Listner for popupmenu***********************/
	 @Override
	    public void actionPerformed(ActionEvent event) {
	        JMenuItem menu = (JMenuItem) event.getSource();
	        if (menu == View) {
	            view();
	        } else if (menu == delete) {
	            delete();
	        } 
	    }


	private void delete() {
		// Code for delete
		System.out.println("sdgfsadf");
		
	}


	private void view() {
		// code for view
		System.out.println("adfgfhg");
	}
	
	/************************************************************************/

}

